name: chef
description: "flutter app for make recipes with gemini ai"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  # Contains code to deal with internationalized/localized messages, date and number formatting
  intl: ^0.19.0
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation.
  get_it: ^7.7.0
  # Add the Cupertino Icons to your application.
  cupertino_icons: ^1.0.8
  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^3.2.0
  # Flutter plugin for Firebase Authentication.
  firebase_auth: ^5.1.2
  # Flutter plugin for Firebase Cloud Storage.
  firebase_storage: ^12.1.1
  # Flutter plugin for Cloud Firestore.
  cloud_firestore: ^5.1.0
  # SDK enables to use Google's generative AI models (like Gemini).
  google_generative_ai: ^0.4.3
  # A package to use fonts from fonts.google.com.
  google_fonts: ^6.2.1
  # Flutter Widgets that make it easy to implement the BLoC state management.
  flutter_bloc: ^8.1.6
  # A plugin for adapting screen and font size.
  flutter_screenutil: ^5.9.3
  # A plugin for controlling the camera.
  camera: ^0.11.0+1
  # A plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^1.1.2
  # Explicitly reads environment variables into a dart file from a .env file for more security and faster start up times.
  envied: ^0.5.4+1
  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.1.0
  # Render After Effects animations natively on Flutter.
  lottie: ^3.1.2
  # A plugin for reading and writing simple key-value pairs.Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.2.3
  # Provides API to store data in secure storage.
  flutter_secure_storage: ^9.2.2
  # An SVG rendering and widget library for Flutter.
  flutter_svg: ^2.0.10+1
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^2.4.3
  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.9.0
  # Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
  hive: ^2.2.3
  # Extension for Hive. Makes it easier to use Hive in Flutter apps.
  hive_flutter: ^1.1.0
  # A pure Dart library that checks for internet by opening a socket to a list of specified addresses.
  internet_connection_checker: ^1.0.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^4.0.0
  # Generator for the Envied package.
  envied_generator: ^0.5.4+1
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.11
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.5.2
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0
  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^2.0.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/animations/


flutter_assets_generator:
  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on lib dir. Default: generated
  output_dir: lib/core/utils/app_assets
  # Optional. Sets the name for the generated localization file. Default: assets
  output_filename: app_assets
  # Optional. Sets the name for the generated localization class. Default: Assets
  class_name: AppAssets