name: chef
description: "flutter app for make recipes with gemini ai"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # Add the Cupertino Icons to your application.
  cupertino_icons: ^1.0.8
  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^3.1.1
  # SDK enables to use Google's generative AI models (like Gemini).
  google_generative_ai: ^0.4.3
  # A package to use fonts from fonts.google.com..
  google_fonts: ^6.2.1
  # Flutter Widgets that make it easy to implement the BLoC state management
  flutter_bloc: ^8.1.6
  # A plugin for adapting screen and font size
  flutter_screenutil: ^5.9.3
  # A plugin for controlling the camera.
  camera: ^0.11.0+1
  # A plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^1.1.2
  # Explicitly reads environment variables into a dart file from a .env file for more security and faster start up times.
  envied: ^0.5.4+1
  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^4.0.0
  # Generator for the Envied package
  envied_generator: ^0.5.4+1
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.11
flutter:
  generate: true
  uses-material-design: true