// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCobq4UL_4d1VbT-ZBeSa1lRWpadST2cpI',
    appId: '1:219005004618:web:b43372591c1f99e74a2fb3',
    messagingSenderId: '219005004618',
    projectId: 'chefbot-1455a',
    authDomain: 'chefbot-1455a.firebaseapp.com',
    storageBucket: 'chefbot-1455a.appspot.com',
    measurementId: 'G-7JFZJ78TVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnRNaWQuR45d7Jatnf6qUBwDw36P3mxb0',
    appId: '1:219005004618:android:85bb9fd98dff76314a2fb3',
    messagingSenderId: '219005004618',
    projectId: 'chefbot-1455a',
    storageBucket: 'chefbot-1455a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQVUIIrSRHL4k9UT9nc16fOZmXFIghe90',
    appId: '1:219005004618:ios:f5b9bbe9ba444e4f4a2fb3',
    messagingSenderId: '219005004618',
    projectId: 'chefbot-1455a',
    storageBucket: 'chefbot-1455a.appspot.com',
    iosBundleId: 'com.chefBot.chef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQVUIIrSRHL4k9UT9nc16fOZmXFIghe90',
    appId: '1:219005004618:ios:2f1f9746df0f362a4a2fb3',
    messagingSenderId: '219005004618',
    projectId: 'chefbot-1455a',
    storageBucket: 'chefbot-1455a.appspot.com',
    iosBundleId: 'com.chefBot.chef.RunnerTests',
  );
}
